export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const EDIT_ORDER_SUCCESS = "EDIT_ORDER_SUCCESS";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const ORDER_ERROR = "ORDER_ERROR";